name: "Example 1: Basic usage"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "develop"
      - "main"
      - "master"

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        python-version: ["3.10"]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: conda install pyfftw
        shell: bash -el {0}
        run: |
          conda config --add channels conda-forge
          conda install pyfftw
          conda list
      - name: pip install finufft
        shell: bash -el {0}
        run: pip install "finufft==2.2.0"
      - name: pip list
        shell: bash -el {0}
        run: pip list
      - name: python run
        shell: bash -el {0}
        run: python test_finufft_plan.py
